#### DTU {#resultsRnaseqSRP131063DTU}

##### Fluoxetine VS Methylcellulose {#resultsRnaseqSRP131063DTUFluoxetineVsMethylcellulose}


```{r resultsRnaseqSRP131063DTUFluoxetineVsMethylcellulose}
sse <- se[
  ,
  se$group %in% c(
    "stress.saline",
    "stress.fluoxetine"
  )
]
comparison_var_name <- "group"

sse$group <- droplevels(sse$group)

sse <- labelKeep(sse)
sse <- sse[mcols(sse)$keep,]
set.seed(1)
sse <- swish(
  sse,
  x = comparison_var_name
)
table(mcols(sse)$qvalue < .05)

most.sig <- with(
  mcols(sse),
  order(
    qvalue,
    -abs(log2FC)
  )
)
mcols(sse)[
  head(most.sig),
  c(
    "log2FC",
    "qvalue"
  )
]
hist(
  mcols(sse)$pvalue,
  col = "grey"
)

with(
  mcols(sse),
  table(
    sig = qvalue < .05,
    sign.lfc = sign(log2FC)
  )
)

#sig <- mcols(sse)$qvalue < .05
#lo <- order(mcols(sse)$log2FC * sig)
#hi <- order(-mcols(sse)$log2FC * sig)

top <- mcols(sse)[order(mcols(sse)$pvalue),]
top_up <- top[sign(top$log2FC) == 1,]
top_down <- top[sign(top$log2FC) == -1,]
top_up <- top_up[1:250,]
top_down <- top_down[1:250,]

cols <- c(
  "tx_id",
  "SYMBOL",
  "log10mean",
  "log2FC",
  "pvalue",
  "qvalue"
)

write.xlsx(
  top[,cols],
  file.path(
    book_from_rmd,
    "xlsx",
    paste0(
      opts_current$get("label"),
      ".xlsx"
    )
  )
)

rm(top)
```

```{r resultsRnaseqSRP131063DTUFluoxetineVsMethylcelluloseTopUp, fig.cap="Top upregulated isoforms"}
produceDataTableWithButtons(as.data.frame(top_up)[,cols])
```

```{r resultsRnaseqSRP131063DTUFluoxetineVsMethylcelluloseTopDn, fig.cap="Top downregulated isoforms"}
produceDataTableWithButtons(as.data.frame(top_down)[,cols])
```

The complete table for all transcripts passing the [labelKeep](https://rdrr.io/bioc/fishpond/man/labelKeep.html) default filter is available [here](xlsx/resultsRnaseqSRP131063DTUFluoxetineVsMethylcellulose.xlsx).

```{r resultsRnaseqSRP131063DTUFluoxetineVsMethylcellulosePlotInfRepsTopUp, fig.cap = "Distribution of inferential replicates for the top upregulated isoform, for each sample, splitted by condition"}
plotInfReps(
  sse,
  idx=top_up[1,"tx_id"],
  #cov = "tissue_region",
  x = comparison_var_name
)
```

```{r resultsRnaseqSRP131063DTUFluoxetineVsMethylcellulosePlotInfRepsTopDn, fig.cap="Distribution of inferential replicates for the top downregulated isoform, for each sample, splitted by condition"}
plotInfReps(
  sse,
  idx=top_down[1,"tx_id"],
  #cov = "tissue_region",
  x = comparison_var_name
)
```
```{r resultsRnaseqSRP131063DTUFluoxetineVsMethylcellulosePlotIsoTopUp, fig.cap="TPM, isoform proportion and raw counts for the top upregulated isoform, for each sample, splitted by condition", fig.width=12}
d <- reshape2::melt(
  data.frame(
    isoProp = as.vector(assays(sse[mcols(sse)$tx_id %in% top_up[1,"tx_id"]])$isoProp),
    TPM = as.vector(assays(sse[mcols(sse)$tx_id %in% top_up[1,"tx_id"]])$abundance),
    Raw = as.vector(assay(sse[mcols(sse)$tx_id %in% top_up[1,"tx_id"]])),
    colData(sse)[
      ,
      c(
        "sample_title",
        "group"
      )
    ]
  )
)
p <- ggplot(
  d,
  aes(
    x = sample_title,
    y = value,
    fill = group
  )
)
p <- p + geom_bar(stat="identity")
p <- p + facet_nested(
  variable ~ group,
  scales="free"
)
p <- p + theme(
  axis.text.x = element_text(
    angle = 45,
    hjust = 1,
    vjust = 1
  )
)
p <- p + ggtitle(top_up[1,"tx_id"])
p
```

```{r resultsRnaseqSRP131063DTUFluoxetineVsMethylcellulosePlotIsoTopDn, fig.cap="TPM, isoform proportion and raw counts for the top downregulated isoform, for each sample, splitted by condition", fig.width=12}
d <- reshape2::melt(
  data.frame(
    isoProp = as.vector(assays(sse[mcols(sse)$tx_id %in% top_down[1,"tx_id"]])$isoProp),
    TPM = as.vector(assays(sse[mcols(sse)$tx_id %in% top_down[1,"tx_id"]])$abundance),
    Raw = as.vector(assay(sse[mcols(sse)$tx_id %in% top_down[1,"tx_id"]])),
    colData(sse)[
      ,
      c(
        "sample_title",
        "group"
      )
    ]
  )
)
p <- ggplot(
  d,
  aes(
    x = sample_title,
    y = value,
    fill = group
  )
)
p <- p + geom_bar(stat="identity")
p <- p + facet_nested(
  variable ~ group,
  scales="free"
)
p <- p + theme(
  axis.text.x = element_text(
    angle = 45,
    hjust = 1,
    vjust = 1
  )
)
p <- p + ggtitle(top_down[1,"tx_id"])
p
```

```{r resultsRnaseqSRP131063DTUFluoxetineVsMethylcellulosePlotMA, fig.cap="MA-plot with blue-highlighted genes corresponding to those with qvalue < 0.1"}
plotMASwish(
  sse,
  alpha = .05,
  xlim = c(.5,5.5)
)
signifs <- subset(
  mcols(sse),
  qvalue < .1 #& abs(log2FC) > 1
)
if (nrow(signifs) > 0) {
  with(
    signifs,
    text(
      log10mean,
      log2FC,
      SYMBOL,
      col = "blue",
      pos = 4,
      cex = .7
    )
  )
}
```
