#### DEA {#resultsRnaseqSRP131063DEA}

##### Fluoxetine VS Saline for Stressed {#resultsRnaseqSRP131063FluoxetineVsSalineForStressed}

###### Apeglm {#resultsRnaseqSRP131063FluoxetineVsSalineForStressedApeglm}

```{r resultsRnaseqSRP131063FluoxetineVsSalineForStressedApeglmComputeDeseq2}
dds <- DESeqDataSetFromMatrix(
  countData = SRP131063_raw[, -1],
  colData = SRP131063_metadata,
  rowData = SRP131063_genes,
  design = ~group
)

# Unsure to filter genes here
# Because I want to be able to see them
# if they are DE in another experiment.
keep <- rowSums(counts(dds)) >= ncol(counts(dds))
dds <- dds[keep, ]

dds <- DESeq(dds)
resultsNames(dds) # lists the coefficients

# vsd <- varianceStabilizingTransformation(dds)

res <- lfcShrink(
  dds,
  coef = "group_stress.fluoxetine_vs_stress.saline",
  type = "apeglm"
)
```

```{r resultsRnaseqSRP131063FluoxetineVsSalineForStressedApeglmKnitPostDeseq2, results="asis", cache=FALSE}
knitPostDeseq2Template(
  FC_cutoff = 0.5,
  cols = rat_cols
)

res$project <- "SRP131063"
res$comparison <- "FluoxetineVsSalineForStressed"

dea_res$rnaseq$SRP131063$FluoxetineVsSalineForStressed <- cbind(
  mcols(dds)[, 1:4],
  res
)
```

